project:
  type: website

website:
  title: "My Portfolio"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: Zombies.qmd
        text: Zombies!
      - href: EEB406_redo.qmd
        text: EEB406 ReDo
